// <auto-generated />
using System;
using DnDiscordAPI.Games.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DnDiscordAPI.Games.Database.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    partial class GamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DnDiscordAPI.Games.Character.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AsiAppliedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DnDiscordAPI.Games.Inventory.Models.InventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("InventoryEntries", (string)null);
                });

            modelBuilder.Entity("DnDiscordAPI.Games.Inventory.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GoldCost")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Category = 0,
                            Description = "Une fiole emplie d'un liquide rouge vif qui semble bouillonner doucement, même au repos.",
                            GoldCost = 50,
                            Icon = "potion-red",
                            Name = "Potion de soin"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Category = 0,
                            Description = "Un flacon au liquide bleu nuit parcouru d'éclats scintillants, comme un ciel étoilé en miniature.",
                            GoldCost = 50,
                            Icon = "potion-blue",
                            Name = "Potion de mana"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Category = 3,
                            Description = "Un bâton de bois enduit de résine à son extrémité, prêt à être allumé pour éclairer les ténèbres.",
                            GoldCost = 1,
                            Icon = "torch",
                            Name = "Torche"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Category = 0,
                            Description = "Un paquet soigneusement emballé contenant du pain dur, de la viande séchée et un morceau de fromage.",
                            GoldCost = 5,
                            Icon = "bread",
                            Name = "Ration de voyage"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Category = 3,
                            Description = "Une longue corde en chanvre tressé, solide et fiable, indispensable pour tout aventurier.",
                            GoldCost = 1,
                            Icon = "rope",
                            Name = "Corde en chanvre"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            Category = 1,
                            Description = "Une lame courte et effilée, parfaite pour les coups rapides ou un lancer précis.",
                            GoldCost = 25,
                            Icon = "dagger",
                            Name = "Dague affûtée"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            Category = 1,
                            Description = "Un arc léger en bois d'if, idéal pour la chasse et les escarmouches à distance.",
                            GoldCost = 50,
                            Icon = "bow",
                            Name = "Arc court"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            Category = 2,
                            Description = "Un bouclier rond en acier forgé, marqué par les coups de batailles passées.",
                            GoldCost = 75,
                            Icon = "shield",
                            Name = "Bouclier en acier"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000009"),
                            Category = 4,
                            Description = "Un vieux parchemin couvert de runes argentées qui luisent faiblement dans l'obscurité.",
                            GoldCost = 150,
                            Icon = "scroll",
                            Name = "Parchemin de sort"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-00000000000a"),
                            Category = 5,
                            Description = "Un petit coffre en bois cerclé de fer, fermé par un cadenas rouillé. On entend quelque chose tinter à l'intérieur.",
                            GoldCost = 0,
                            Icon = "chest",
                            Name = "Coffre au trésor"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-00000000000b"),
                            Category = 4,
                            Description = "Un pendentif en bronze patiné, orné d'un œil gravé qui semble suivre du regard quiconque le porte.",
                            GoldCost = 200,
                            Icon = "amulet",
                            Name = "Amulette ancienne"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-00000000000c"),
                            Category = 5,
                            Description = "Un parchemin jauni et usé, marqué d'un grand X rouge. L'encre semble ancienne mais la carte reste lisible.",
                            GoldCost = 0,
                            Icon = "map",
                            Name = "Carte au trésor"
                        });
                });

            modelBuilder.Entity("DnDiscordAPI.Games.Character.Models.Character", b =>
                {
                    b.OwnsOne("DnDiscordAPI.Games.Character.Models.AbilityScores", "Abilities", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Charisma")
                                .HasColumnType("integer");

                            b1.Property<int>("Constitution")
                                .HasColumnType("integer");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("integer");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("DnDiscordAPI.Games.Character.Models.Wallet", "Wallet", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CopperPieces")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<int>("ElectrumPieces")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<int>("GoldPieces")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<int>("PlatinumPieces")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<int>("SilverPieces")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Abilities")
                        .IsRequired();

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("DnDiscordAPI.Games.Inventory.Models.InventoryEntry", b =>
                {
                    b.HasOne("DnDiscordAPI.Games.Character.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDiscordAPI.Games.Inventory.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
